// --- DOM Elements ---
export const elements = {
    // Header
    clock: document.getElementById('clock'),
    date: document.getElementById('date'),
    greeting: document.getElementById('greeting'),
    // Timer
    time: document.getElementById('time'),
    ring: document.querySelector('.progress-ring__circle'),
    thumb: document.querySelector('.progress-ring__thumb'),
    startBtn: document.getElementById('start-btn'),
    resetBtn: document.getElementById('reset-btn'),
    soundBtn: document.getElementById('toggle-sound'),
    status: document.getElementById('timer-status'),
    taskSelect: document.getElementById('focus-task-select'),
    // To-Do
    todoInput: document.getElementById('todo-input'),
    addTodoBtn: document.getElementById('add-todo'),
    todoList: document.getElementById('todo-list'),
    // Calendar & Analysis
    historyPanel: document.querySelector('.history-panel'),
    bitsPanel: document.querySelector('.bits-panel'),
    calendarGrid: document.getElementById('mini-calendar'),
    todayFocus: document.getElementById('today-focus'),
    calendarView: document.getElementById('calendar-view'),
    analysisView: document.getElementById('analysis-view'),
    viewToggleBtn: document.getElementById('view-toggle-btn'),
    todayFocusBtn: document.getElementById('today-focus-btn'),
    analysisDateText: document.getElementById('analysis-date'),
    focusChart: document.getElementById('focus-chart'),
    analysisSessions: document.getElementById('analysis-sessions'),
    prevDayBtn: document.getElementById('prev-day'),
    nextDayBtn: document.getElementById('next-day'),
    // Quote
    quoteText: document.getElementById('quote-text'),
    quoteAuthor: document.getElementById('quote-author'),
    newQuoteBtn: document.getElementById('new-quote'),
    // Settings
    settingsBtn: document.getElementById('settings-btn'),
    settingsModal: document.getElementById('settings-modal'),
    closeSettingsBtn: document.getElementById('close-settings'),
    presetBtns: document.querySelectorAll('.preset-btn'),
    bgUpload: document.getElementById('bg-upload'),
    userNameInput: document.getElementById('user-name'),
    // About
    aboutBtn: document.getElementById('about-btn'),
    aboutModal: document.getElementById('about-modal'),
    closeAboutModal: document.getElementById('close-about-modal'),
    // Modular Widgets
    switchBtns: document.querySelectorAll('.switch-btn'),
    widgetContents: document.querySelectorAll('.widget-content'),
    starsCanvas: document.getElementById('stars-canvas'),
    shuffleStarsBtn: document.getElementById('shuffle-stars'),
    starsInfoBtn: document.getElementById('stars-info-btn'),
    starsMainView: document.getElementById('stars-main-view'),
    starsHierarchyView: document.getElementById('stars-hierarchy-view'),
    closeStarsHierarchyBtn: document.getElementById('close-stars-hierarchy'),
    starsHierarchyList: document.getElementById('stars-hierarchy-list'),
    petDisplay: document.getElementById('pet-display'),
    petName: document.getElementById('pet-name'),
    petStatus: document.getElementById('pet-status'),
    petMainView: document.getElementById('pet-main-view'),
    petHierarchyView: document.getElementById('pet-hierarchy-view'),
    closePetHierarchyBtn: document.getElementById('close-pet-hierarchy'),
    petHierarchyList: document.getElementById('pet-hierarchy-list'),
    petInfoBtn: document.getElementById('pet-info-btn'),
    bitInfoBtn: document.getElementById('bit-info-btn'),
    bitDrawer: document.getElementById('bit-drawer'),
    bitDrawerTitle: document.getElementById('bit-drawer-title'),
    bitDrawerDesc: document.getElementById('bit-drawer-desc'),
    // Corner Widgets & Presets
    ambientIndicators: document.querySelectorAll('#ambient-indicators i'),
    focusVisualizer: document.getElementById('focus-visualizer'),
    presetTimes: document.querySelectorAll('.preset-time'),
};
